### ISSUE TITLE
AngularJS Batarang 0.8.5 Scope's Models show nothing

### ISSUE THREAD

**Issue by doggy8088** [angular/batarang#249] opened 2015-07-22 08:46 UTC
I've got this error when debugging [this page](http://output.jsbin.com/yutej) using [AngularJS Batarang 0.8.15](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk).

There is no error occurred.  It just nothing show up in the "Models" pane in the "Scopes" tab.  Here is a screenshot below:

![image](https://cloud.githubusercontent.com/assets/88981/8821539/fe7fdbc6-3090-11e5-93c8-3f930d7c8205.png)

**Comment by gary-b** [comment] 2015-07-22 22:56
Are you debugging an angular 1.2.x app? This is a known issue if so. A pull request has been submitted which fixes it, so hopefully the issue will be resolved shortly.

**Comment by doggy8088** [comment] 2015-07-23 08:44
Yes, you're right.  After I change to 1.3.15 ( [this page](http://output.jsbin.com/dabecuqibi) ), the problem solved.  Thanks!

**Comment by gary-b** [comment] 2015-07-23 17:07
No problem. :)

**Comment by SomeKittens** [comment] 2015-08-27 21:34
@doggy8088 thanks for bringing this to our attention, closing as a dupe of #231

**Closed by SomeKittens** 2015-08-27 21:34 UTC
