### ISSUE TITLE
Cannot read property 'invoke' of undefined

### ISSUE THREAD

**Issue by spalger** [angular/batarang#182] opened 2014-12-10 17:22 UTC
Apparently batarang is now overriding methods on the angular object, which I'm not entirely against but it shouldn't be hard to make them work they way they originally did.

Consider using sinon spies, or an ES6 Proxy shim instead.

[This line of code](https://github.com/elasticsearch/kibana/blob/master/src/kibana/index.js#L67) is producing the "Cannot read property 'invoke' of undefined" mentioned in the title.

**Comment by SomeKittens** [comment] 2015-09-30 21:08
Duplicate of https://github.com/angular/batarang/issues/163

Angular proper doesn't support this, sorry.

**Closed by SomeKittens** 2015-09-30 21:08 UTC
Labels: type: bug
