### ISSUE TITLE
Broken when running with jsfiddle

### ISSUE THREAD

**Issue by angulargirl** [angular/batarang#89] opened 2013-11-21 15:39 UTC
http://stackoverflow.com/questions/20107490/confirm-that-batarang-is-broken

Detailed with images that are included in above link

**Comment by SomeKittens** [comment] 2015-11-12 21:23
This is because we don't currently support iframes (and JSFiddle displays the result of your code in an iframe).

Dupe of #14

**Closed by SomeKittens** 2015-11-12 21:23 UTC
