### ISSUE TITLE
Batarang breaks ng-mouseenter and ng-mouseleave

### ISSUE THREAD

**Issue by WillsB3** [angular/batarang#202] opened 2015-01-05 12:09 UTC
I have no idea how this happens, but we had a problem today where Batarang caused incorrect/broken behaviour for these 2 events.

ng-mouseenter would fire 3 times instead of once, and ng-mouseleave would simply never fire at all.

I'm not sure if this was a result of some weird usage of these events inside an ng-repeat for example, but everything works fine and as expected with Batarang disabled.

I was using version 0.7.4.

**Comment by shahata** [comment] 2015-01-05 13:51
This is fixed by https://github.com/angular/angular-hint-events/pull/10

**Comment by makenova** [comment] 2015-01-05 19:17
I'm having a similar issue with version 0.7.4
Only the event that is listed first will fire when Batarang is enabled.

**Comment by uiman** [comment] 2015-01-08 20:33
Thanks for posting this! I'm having the same issue in both 0.7.4 and 0.4.3 versions

**Comment by makenova** [comment] 2015-01-09 00:53
@uiman, until there is a new release of Batarang, you can fix this by running the extension from the source and updating the `angular-hint-event` dependency.
Instructions for running from source can be found [**here**](https://github.com/angular/angularjs-batarang/blob/master/CONTRIBUTING.md#installing-from-source)

**Comment by gary-b** [comment] 2015-07-19 21:30
This looks like #205, which we have confirmed as resolved.

**Closed** 2015-08-11 00:22 UTC
Labels: type: bug
