### ISSUE TITLE
Batarang with angularjs 1.5 

### ISSUE THREAD

**Issue by johndoejdg** [angular/batarang#288] opened 2016-02-19 12:01 UTC
After upgrading angular from 1.4.9 to 1.5.0 batarang start throw many errors in console. Nothing broke in app but it add mass unnecessary information. Please fix it or help me hide it errors. 

20 
> TypeError: Cannot read property '$id' of undefined
>     at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2001:19)
>     at Scope.$digest (http://crm.dev/vendors/assets/angular/angular.js:16664:23)
>     at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2016:23)
>     at Scope.$apply (http://crm.dev/vendors/assets/angular/angular.js:16928:24)
>     at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2079:22)
>     at bootstrapApply (http://crm.dev/vendors/assets/angular/angular.js:1694:15)
>     at Object.invoke (http://crm.dev/vendors/assets/angular/angular.js:4604:19)
>     at doBootstrap (http://crm.dev/vendors/assets/angular/angular.js:1692:14)
>     at Object.angular.resumeBootstrap (http://crm.dev/vendors/assets/angular/angular.js:1720:12)
>     at maybeBootstrap (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:569:11)

1359

> angular.js:13236 TypeError: Cannot read property '$id' of undefined
>     at arguments.(anonymous function) (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2001:19)
>     at Scope.$digest (http://crm.dev/vendors/assets/angular/angular.js:16664:23)
>     at Scope.scopePrototype.$digest (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2016:23)
>     at Scope.$apply (http://crm.dev/vendors/assets/angular/angular.js:16928:24)
>     at Scope.scopePrototype.$apply (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:2079:22)
>     at done (http://crm.dev/vendors/assets/angular/angular.js:11266:47)
>     at completeRequest (http://crm.dev/vendors/assets/angular/angular.js:11464:7)
>     at XMLHttpRequest.requestLoaded (http://crm.dev/vendors/assets/angular/angular.js:11405:9)

**Comment by gkalpak** [comment] 2016-02-19 15:07
This is a duplicate of #285. It has been fixed in https://github.com/angular/angular-hint/pull/117, but apparently there's been no batarang release since.

**Comment by johndoejdg** [comment] 2016-02-19 15:12
Thank you.

**Closed** 2016-02-19 15:12 UTC

**Comment by SomeKittens** [comment] 2016-02-19 21:43
@btford @erwinmombay can we cut a new release?

**Comment by jmallison** [comment] 2016-02-24 22:08
+1

**Comment by akshaylive** [comment] 2016-02-26 16:09
+1

**Comment by alexandernst** [comment] 2016-03-01 20:19
Yes, please, can we get a new release?

**Comment by wibimaster** [comment] 2016-03-04 08:10
+1
