### ISSUE TITLE
Lexer Error: Unterminated quote at columns 0-1 ['] in expression ['].

### ISSUE THREAD

**Issue by doggy8088** [angular/batarang#232] opened 2015-06-23 03:24 UTC
I've got this error when debugging [this page](http://output.jsbin.com/yutej) using [AngularJS Batarang 0.8.1](https://chrome.google.com/webstore/detail/angularjs-batarang/ighdmehidhipcmcojjgiloacoafjmpfk).  The error message is **[Lexer Error: Unterminated quote at columns 0-1 ['] in expression ['].](https://docs.angularjs.org/error/$parse/lexerr?p0=Unterminated%20quote&p1=s%200-1%20%5B%27%5D&p2=%27)**.  It looks like a ngHint problem.  Here is a screenshot below:

![image](https://cloud.githubusercontent.com/assets/88981/8298347/4df201e2-199a-11e5-802e-784d77577bbc.png)

**Comment by erwinmombay** [comment] 2015-06-23 03:45
woot, nice bug find. surprised it only got reported now. Will look into it this week. Thank you for the demo!

**Comment by erwinmombay** [comment] 2015-06-25 02:51
issue related to https://github.com/angular/angularjs-batarang/issues/227

the problem is in the events module at https://github.com/angular/angular-hint/blob/master/src/modules/events.js#L14

**Comment by rainboxx** [comment] 2015-06-26 13:53
This might be a similar issue:

![bildschirmfoto 2015-06-26 um 15 52 41](https://cloud.githubusercontent.com/assets/301178/8378686/6cd09d02-1c1b-11e5-9f83-c834a11af662.png)

Once I deactivate Batarang, everything works fine. This came up in the recent days so it was probably introduced with v0.8.0.

**Comment by doggy8088** [comment] 2015-07-01 16:58
@erwinmombay Do you figure out the solution for this issue?

**Comment by SomeKittens** [comment] 2015-07-04 18:06
Still being worked on, might have a fix tomorrow.  Looks like there's a whole host of problems related to this.

**Comment by erwinmombay** [comment] 2015-07-06 21:54
@doggy8088 sorry not yet was out for a few days. will get back on this. apologies for the wait!

**Comment by erwinmombay** [comment] 2015-07-09 01:41
@doggy8088 finally got a fix for this! hold tight!

**Comment by rainboxx** [comment] 2015-07-09 06:54
Yay!

**Comment by doggy8088** [comment] 2015-07-09 12:04
@erwinmombay Great job! :+1:

**Comment by ghar** [comment] 2015-07-09 21:33
:) just ran into this myself.

**Comment by erwinmombay** [comment] 2015-07-09 23:06
fix landed in https://github.com/angular/angular-hint/commit/26cfc749113a599a1e11a587091c558ee2e499b6

**Closed by erwinmombay** 2015-07-09 23:06 UTC

**Comment by ghar** [comment] 2015-07-09 23:48
Worked for me. Thank you!

**Comment by doggy8088** [comment] 2015-07-10 17:13
Thanks! The error in the console is gone, but all the "Scopes" information was just disappeared. :cry: 

The same [example](http://output.jsbin.com/yutej) to try, screenshot below:

![image](https://cloud.githubusercontent.com/assets/88981/8624352/cfc26ed2-2769-11e5-8080-671a631179ea.png)

**Comment by erwinmombay** [comment] 2015-07-24 17:00
@doggy8088 will take a look at that problem this weekend! ill see if theres a related issue somewhere
