### ISSUE TITLE
Failed to instantiate module ngHintModules

### ISSUE THREAD

**Issue by nstanard** [angular/batarang#314] opened 2017-05-09 15:53 UTC
Will update this as I find out more. My app won't load with Batarang 0.10.9 though.

```
Failed to instantiate module ngHintModules due to:
TypeError: Cannot read property 'name' of undefined
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1060:20)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1066:7
    at Array.forEach (native)
    at module.exports (chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1064:21)
    at chrome-extension://ighdmehidhipcmcojjgiloacoafjmpfk/dist/hint.js:1360:5
    at Object.invoke (http://dev.eds.com:8080/analyst-ng/bin/external/angular.min-1.5.8.js:41:456)
    at d (http://dev.eds.com:8080/analyst-ng/bin/external/angular.min-1.5.8.js:39:418)
    at http://dev.eds.com:8080/analyst-ng/bin/external/angular.min-1.5.8.js:40:19
    at q (http://dev.eds.com:8080/analyst-ng/bin/external/angular.min-1.5.8.js:7:355)
    at g (http://dev.eds.com:8080/analyst-ng/bin/external/angular.min-1.5.8.js:39:319
```

**Comment by Peter-Optiway** [comment] 2017-06-26 06:29
I get the exact same issue when i try to load batarang in our angular 1.5.8 application..
Im using `AngularJS Batarang 0.10.9`.

**Comment by 130n** [comment] 2017-07-26 14:30
I started having the same problems recently with angular 1.5.9 and Batarang 0.10.9.

If I reload the page it's fails on `angular.resumeBootstrap` half the time but if I do a hard reload it works.

**Comment by gkalpak** [comment] 2018-02-15 20:20
I can't reproduce this. I am going to close this, but happy to re-open and investigate if someone can provide a reproduction.

**Closed as completed by gkalpak** 2018-02-15 20:20 UTC
