### ISSUE TITLE
Breaks Angular, resulting in raw brackets on page

### ISSUE THREAD

**Issue by tao12345666333** [angular/batarang#254] opened 2015-08-27 03:43 UTC
My AngularJS 1.4 application does not work well in Chrome version 41.0.2272.118(64 bit) with batarang extension  0.8.5.  

![2015-08-27 10 17 36](https://cloud.githubusercontent.com/assets/3264292/9512097/66d5f904-4cb0-11e5-9978-1502cc90a8d4.png)

![2015-08-27 10 18 12](https://cloud.githubusercontent.com/assets/3264292/9512103/82e99a56-4cb0-11e5-9b50-81fe9e6211eb.png)

When I stop the extension and refresh page, it works well.

And when I use the batarang extension with  many times refresh, sometimes it works.

![2015-08-27 10 20 45](https://cloud.githubusercontent.com/assets/3264292/9512110/909905a6-4cb0-11e5-8c56-333051412bcd.png)

**Comment by bratzelk** [comment] 2015-09-02 06:12
I can confirm this problem too.

Batarang:  0.8.6
Angular: 1.3
Chrome: 44.0.2403.157 m

**Comment by SomeKittens** [comment] 2015-09-02 06:36
We can't do much here without reproduction steps.  Good to know versions but a Plunkr/JSBin does wonders.

**Comment by tao12345666333** [comment] 2015-09-04 15:23
Hi, @SomeKittens here is my code and new screenshot.

 [Plunkr Code link ](http://plnkr.co/edit/qO27pmVTgJUBhypHJyYN?p=preview)

![2015-09-04-220600_766x243_scrot](https://cloud.githubusercontent.com/assets/3264292/9687309/52b9460e-535b-11e5-94d4-c65bd4b8fc0d.png)

result.
![2015-09-04-220631_665x413_scrot](https://cloud.githubusercontent.com/assets/3264292/9687325/5cbf76f0-535b-11e5-8d1c-bc725105bb4d.png)


And Chrome has update batarang to 0.8.6
![2015-09-04-220715_746x185_scrot](https://cloud.githubusercontent.com/assets/3264292/9687337/7503173a-535b-11e5-808d-833b35067d69.png)

**Comment by SomeKittens** [comment] 2015-09-10 21:39
I tried with both `0.8.6` and `0.8.7` as well as the min and non-min versions of Angular could not reproduce the issue.  Closing for now.

**Closed by SomeKittens** 2015-09-10 21:39 UTC
Labels: needs: reproduction
