### ISSUE TITLE
One-time binding fail due to Angular Batarang 0.8.6

### ISSUE THREAD

**Issue by doggy8088** [angular/batarang#255] opened 2015-08-28 01:28 UTC
When I enabled the **Angular Batarang 0.8.6**, the "One-time binding" feature will be disabled.  I'm using AngularJS 1.4.  You can reproduce this problem at  [this page](http://output.jsbin.com/safahi).  Please try to enter something in the first input field.  ( default value is **T-Shirt** and there is a angular expression below the form fields )

**Comment by SomeKittens** [comment] 2015-08-28 15:39
I was not able to reproduce.  Are you sure you're on Batarang 0.8.6?  (and not Batarang "Stable", which is not associated with the project at all?)

**Comment by kkFelix** [comment] 2015-08-28 17:42
+1, definitely with Batarang 0.8.6
```
<p>{{::foo}}!</p>
<button ng-click="foo = 'bar'">click</button>
```

"foo" keeps it initial value on click if Batarang is disabled, which is the desired behavior.
When activated, foo changes to "bar".

**Comment by SomeKittens** [comment] 2015-08-28 20:21
Not just Angular 1.4, was able to repro with 1.3 here: http://output.jsbin.com/warariduci

**Comment by erwinmombay** [comment] 2015-08-30 02:21
ill take this. 
problem exists in: https://github.com/angular/angular-hint/blob/master/src/modules/scopes.js#L85

we need to skip doing any perf watching if the interpolation functions expression is a one time binding. we previously did this with strings that where one time bindings (can be seen a couple of lines prior to line 85).

**Comment by erwinmombay** [comment] 2015-08-30 05:57
@SomeKittens @btford i'll need to discuss the solution with you guys on thursday since it seems pretty hacky (again related to the fact we the decorate the original expressions) and it might not make sense to fix it since batarang doesn't expose the watch performance on the panels at the moment.

**Comment by SomeKittens** [comment] 2015-08-30 17:48
Fixed in 0b98cfacc62247b0ceed46c523385e588a55190d

**Closed by SomeKittens** 2015-08-30 17:48 UTC
Labels: type: bug

**Comment by preethi29** [comment] 2016-02-08 06:53
Am able to reproduce this 0.10.5 batarang and angular 1.3.8

**Comment by SomeKittens** [comment] 2016-02-08 16:51
@preethi29 Please include a Plunkr or JSBin with your reproduction.
