### ISSUE TITLE
build 1.5.0-build.4376+sha.aff74ec and batarang

### ISSUE THREAD

**Issue by SanderElias** [angular/batarang#279] opened 2015-11-07 13:00 UTC
If you use the .component helper form this build, and you have batarang active, the following error will be thrown.

`script.js:8 Uncaught TypeError: angular.module(...).component is not a function`

Took me some time to figure out what was happening... 
Disable batarang, and your component(s) start working!

Posted here also as sugessted in  [#13275](https://github.com/angular/angular.js/issues/13275#issuecomment-154694862)

**Comment by Narretz** [comment] 2015-11-09 21:21
@btford @SomeKittens Do you know what could be causing this? I assume batarang decorates the angular.Module functions / or provides its own implementation, and .component isn't yet part of that.

**Comment by SomeKittens** [comment] 2015-11-10 00:44
@Narretz Yep, that'd be the first place to look.  I've got some time, checking into this

**Comment by SomeKittens** [comment] 2015-11-10 00:49
Here's the relevant code:


```javascript
angular.module = function(name, requiresOriginal) {
  var module = originalAngularModule.apply(this, arguments),
      name = module.name;

  module.requiresOriginal = requiresOriginal;
  modules[name] = module;
  var modToCheck = getModule(name, true);
  //check arguments to determine if called as setter or getter
  var modIsSetter = arguments.length > 1;

  if (modIsSetter) {
    hasNameSpace(name);
  }

  if(modToCheck && modToCheck.requiresOriginal !== module.requiresOriginal && modIsSetter) {
    if(!modData.createdMulti[name]) {
      modData.createdMulti[name] = [getModule(name,true)];
    }
    modData.createdMulti[name].push(module);
  }
  modData.createdModules[name] = module;
  return module;
};```

Since we're returning the result of a call to the original `module` function, I'm going to punt this back over the fence.

**Comment by SanderElias** [comment] 2015-11-10 06:22
hmm. probably `.component` will get attached later, as it is an extension on `.directive`. It seems batarang gets in between there. I wonder how that could happen. One would think that those things are handed around per reference.

**Comment by gkalpak** [comment] 2015-11-10 07:40
I still think the problem is within Batarang. It is somehow defining `window.angular` I think, so it is already defined when [`setupModuleLoader()`][1] is executed, thus our [factory function][2] is never called.

Will have to take a closer look to make sure, though.

[1]: https://github.com/angular/angular.js/blob/54e816552f20e198e14f849cdb2379fed8570c1a/src/loader.js#L12
[2]: https://github.com/angular/angular.js/blob/54e816552f20e198e14f849cdb2379fed8570c1a/src/loader.js#L27-L458

**Comment by gkalpak** [comment] 2015-11-10 07:45
Hm...yes, Batarang seems to have [it's own loader][1] (to retain comptibility with `v1.2.x` ?).
So, it needs to get updated to include `.component` I guess.

I'm punting this ba...ehm...re-opening this.

[1]: https://github.com/angular/batarang/blob/37fc5e2d1b60dd71473e75ba168dfd4e42e6e176/loader.js#L92-L412

**Comment by SomeKittens** [comment] 2015-11-11 02:41
Well, I never was very good at football anyway.

Yep, that's us, need to fix that loader.  Completely forgot about it.

**Comment by SomeKittens** [comment] 2015-11-12 20:16
y'know what?  Double my bad - this is a dupe of #275

**Closed by SomeKittens** 2015-11-12 20:16 UTC
Labels: type: bug
